Project conflux {
	database_type: 'MySQL'
}

Table "addresses" {
	"address_id" INT [pk, not null]
	"primary" BOOLEAN [not null]
	"line_1" VARCHAR
	"line_2" VARCHAR
	"city" VARCHAR
	"state" VARCHAR
	"zip_code" INT
	"zip_ext" INT
}

Table "companies" {
	"company_id" INT [pk, not null]
	"company_id_parent" INT
	"company_ids_children" VARCHAR
	"name" VARCHAR
	"dba" VARCHAR
	"ein" INT
}

Table "companies_utilities" {
	"companies_utilities_id" INT [pk, not null]
	"company_id" INT [not null]
	"utility_type_id" INT [not null]
}

Table "contacts" {
	"contact_id" INT [pk, not null]
	"company_id" INT [note: 'compound vs composite keys']
	"person_id" INT [note: 'compound vs composite keys']
	"notes" VARCHAR
}

Table "contacts_addresses" {
	"contact_address" INT [pk, not null]
	"contact_id" INT [not null]
	"address_id" INT [not null]
}

Table "emails" {
	"email_id" INT [pk, not null]
	"contact_id" INT [not null]
	"prefix" VARCHAR [not null]
	"subdomain" VARCHAR
	"domain" VARCHAR [not null]
	"extension" VARCHAR [not null]
}

Table "leases" {
	"lease_id" INT [pk, not null]
	"unit_id" INT [not null]
	"sign" DATE
	"start" DATE
	"end" DATE
	"due" DATE
	"rent" INT
	"notes" VARCHAR
}

Table "leases_contacts" {
	"lease_contact_id" INT [pk, not null]
	"contact_id" INT [not null]
	"lease_id" INT [not null]
}

Table "logins" {
	"login_id" INT [pk, not null]
	"contact_id" INT [not null]
	"username" VARCHAR
	"password" VARCHAR
	"url" VARCHAR
	"notes" VARCHAR
}

Table "ownerships" {
	"ownership_id" INT [pk, not null]
	"company_id" INT [not null]
	"contact_id" INT [not null]
	"investment" INT [not null]
	"percentage" INT [not null]
}

Table "payment_schedule" {
	"payment_schedule_id" INT [pk, not null]
	"lease_id" INT
	"amount" INT
	"due" DATE
	"notes" VARCHAR
}

Table "persons" {
	"person_id" INT [pk, not null]
	"name_first" VARCHAR
	"name_middle" VARCHAR
	"name_last" VARCHAR
	"ssn" INT
}

Table "phones" {
	"phone_id" INT [pk, not null]
	"contact_id" INT [not null]
	"country_code" INT [not null, default: 1]
	"area_code" INT [not null]
	"prefix_code" INT [not null]
	"suffix_code" INT [not null]
}

Table "properties" {
	"property_id" INT [pk, not null]
	"contact_id_owner" INT [not null]
	"address_id" INT [not null]
	"parcel_number" VARCHAR
	"notes" VARCHAR
}

Table "units" {
	"unit_id" INT [pk, not null]
	"property_id" INT [not null]
	"address_id" INT [not null]
	"passcode" INT
	"notes" VARCHAR
}

Table "utilities_accounts" {
	"utility_account_id" INT [pk, not null]
	"unit_id" INT [not null]
}

Table "utility_types" {
	"utility_type_id" INT [pk, not null]
	"type" INT [not null]
}

Ref "FK_leases_TO_leases_contacts":"leases"."lease_id" < "leases_contacts"."lease_id"

Ref "FK_contacts_TO_leases_contacts":"contacts"."contact_id" < "leases_contacts"."contact_id"

Ref "FK_properties_TO_units":"properties"."property_id" < "units"."property_id"

Ref "FK_addresses_TO_units":"addresses"."address_id" < "units"."address_id"

Ref "FK_addresses_TO_properties":"addresses"."address_id" < "properties"."address_id"

Ref "FK_units_TO_leases":"units"."unit_id" < "leases"."unit_id"

Ref "FK_contacts_TO_contacts_addresses":"contacts"."contact_id" < "contacts_addresses"."contact_id"

Ref "FK_addresses_TO_contacts_addresses":"addresses"."address_id" < "contacts_addresses"."address_id"

Ref "FK_contacts_TO_phones":"contacts"."contact_id" < "phones"."contact_id"

Ref "FK_contacts_TO_logins":"contacts"."contact_id" < "logins"."contact_id"

Ref "FK_contacts_TO_emails":"contacts"."contact_id" < "emails"."contact_id"

Ref "FK_contacts_TO_properties":"contacts"."contact_id" < "properties"."contact_id_owner"

Ref "FK_companies_TO_companies":"companies"."company_id" < "companies"."company_id_parent"

Ref "FK_companies_TO_contacts":"companies"."company_id" < "contacts"."company_id"

Ref "FK_persons_TO_contacts":"persons"."person_id" < "contacts"."person_id"

Ref "FK_contacts_TO_ownerships":"contacts"."contact_id" < "ownerships"."contact_id"

Ref "FK_companies_TO_ownerships":"companies"."company_id" < "ownerships"."company_id"

Ref "FK_companies_TO_companies_utilities":"companies"."company_id" < "companies_utilities"."company_id"

Ref "FK_utility_types_TO_companies_utilities":"utility_types"."utility_type_id" < "companies_utilities"."utility_type_id"

Ref "FK_units_TO_utilities_accounts":"units"."unit_id" < "utilities_accounts"."unit_id"
